---
- hosts: all
  tasks:
    - name: 'Instala pacotes de dependências do sistema operacional'
      apt:
        name: 
        - php
        - php-fpm
        - apache2
        - libapache2-mod-php
        - php-gd
        - php-ssh2
        - libmcrypt-dev
        - python3-dev
        - libmysqlclient-dev
        - python3-pip
        - php-mysql
        state: latest
      become: yes
      
    - name: instalando mysql-python com pip
      pip:
        name:
          - mysql-connector-python